/**
 * Getting your revision out of SmartRecap.
 *
 * A study tool that traps your notes is a study tool you stop using in week
 * three, so every recap leaves in a format something else already reads:
 * Markdown for Notion and Obsidian, CSV for Anki, and the browser's own print
 * dialogue for a PDF.
 */

const download = (filename, text, mime) => {
  const url = URL.createObjectURL(new Blob([text], { type: `${mime};charset=utf-8` }));
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  // Revoking immediately can cancel the download in Safari.
  setTimeout(() => URL.revokeObjectURL(url), 4000);
};

const safeName = (title) => title.replace(/[^\w\s-]/g, '').trim().replace(/\s+/g, '-').slice(0, 60) || 'recap';

const labelFor = (chunks, ids = []) => {
  const map = new Map(chunks.map((c) => [c.id, c.label]));
  return ids.map((id) => map.get(id)).filter(Boolean);
};

export function toMarkdown(material) {
  const { recap, chunks = [], quiz } = material;
  const lines = [];

  lines.push(`# ${material.title}`, '');
  lines.push(`*${material.module} · ${material.pageCount} pages · ${recap.readMinutes} minute read*`, '');
  lines.push('## Summary', '', recap.summary, '');

  for (const section of recap.sections) {
    lines.push(`## ${section.heading}`, '');
    for (const p of section.points) {
      const cites = labelFor(chunks, p.citations);
      lines.push(`- ${p.text}${cites.length ? ` *(${cites.join(', ')})*` : ''}`);
    }
    lines.push('');
  }

  if (recap.keyTerms?.length) {
    lines.push('## Key terms', '');
    for (const t of recap.keyTerms) {
      const cites = labelFor(chunks, t.citations);
      lines.push(`- **${t.term}** — ${t.definition}${cites.length ? ` *(${cites.join(', ')})*` : ''}`);
    }
    lines.push('');
  }

  if (recap.examTips?.length) {
    lines.push('## Exam tips', '');
    recap.examTips.forEach((tip) => lines.push(`- ${tip}`));
    lines.push('');
  }

  if (recap.ungrounded?.length) {
    lines.push('## Dropped claims', '');
    lines.push('These were generated but could not be traced to the source material, so they are not part of the recap.', '');
    for (const u of recap.ungrounded) {
      lines.push(`- ~~${u.text}~~ — ${u.reason}`);
    }
    lines.push('');
  }

  if (quiz?.questions?.length) {
    lines.push('## Quiz', '');
    quiz.questions.forEach((q, i) => {
      lines.push(`**${i + 1}. ${q.prompt}**${q.verified ? '' : ' *(not scored — unverifiable from the source)*'}`, '');
      q.options.forEach((o, oi) => lines.push(`   ${String.fromCharCode(65 + oi)}. ${o}`));
      lines.push('', `   Answer: ${String.fromCharCode(65 + q.answer)} — ${q.explanation}`, '');
    });
  }

  lines.push('---', `Generated by SmartRecap from ${material.fileName}.`);
  download(`${safeName(material.title)}.md`, lines.join('\n'), 'text/markdown');
}

const csvCell = (v) => `"${String(v).replace(/"/g, '""')}"`;

/** Anki's basic note type: front, back, tags — one row per card. */
export function toAnkiCsv(material) {
  const rows = [];
  const chunks = material.chunks ?? [];
  const tag = (material.module ?? 'SmartRecap').replace(/\s+/g, '_');

  for (const t of material.recap?.keyTerms ?? []) {
    const cites = labelFor(chunks, t.citations);
    rows.push([t.term, `${t.definition}${cites.length ? `<br><i>${cites.join(', ')}</i>` : ''}`, `${tag} KeyTerms`]);
  }

  for (const q of material.quiz?.questions ?? []) {
    if (!q.verified) continue;
    const cites = labelFor(chunks, q.citations);
    rows.push([
      q.prompt,
      `${q.options[q.answer]}<br><br>${q.explanation}${cites.length ? `<br><i>${cites.join(', ')}</i>` : ''}`,
      `${tag} ${q.topic.replace(/\s+/g, '_')}`,
    ]);
  }

  const csv = rows.map((r) => r.map(csvCell).join(',')).join('\n');
  download(`${safeName(material.title)}-anki.csv`, csv, 'text/csv');
  return rows.length;
}

export function printRecap() {
  window.print();
}
