import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { api, openSourcePage } from '../lib/api.js';
import { StudyShell } from '../components/layout/Shells.jsx';
import { CitationProvider, Claim, SourceCard } from '../components/Citations.jsx';
import { Icon, Spinner, Empty, useToast } from '../components/ui.jsx';
import './binder-recap.css';

/**
 * Read-only view of a Binder's Recap.
 *
 * Deliberately smaller than the single-Material `Recap.jsx` — no export
 * panel, no Ask, and the quiz below is shown for reference rather than run
 * live — a Binder's recap is still generated by the same grounded pipeline
 * (`core/binderPipeline.js`) and carries the same citation contract, so it
 * reuses `Citations.jsx` rather than a second implementation of "hover a
 * claim, see its source".
 *
 * Every point, key term and quiz question here may carry `resolvedCitations`
 * — `{ sourceId, displayName, page }[]` produced server-side by
 * `core/citations.js` — on top of the legacy chunk-id `citations`. `Claim`
 * renders the resolved form when present and falls back to the original
 * chunk-label chips otherwise, so a recap generated before this feature
 * existed still renders exactly as it did before.
 */
export default function BinderRecap() {
  const { id } = useParams();
  const toast = useToast();
  const [binder, setBinder] = useState(null);
  const [selectedSources, setSelectedSources] = useState([]);
  const [error, setError] = useState(null);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const full = await api.binders.get(id);
        if (!cancelled) setBinder(full);
      } catch (e) {
        if (!cancelled) setError(e);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [id]);

  const sourcesSummary = binder?.sourcesSummary ?? binder?.sourceProvenance ?? [];
  useEffect(() => {
    if (sourcesSummary.length) setSelectedSources((current) => current.length ? current : sourcesSummary.map((source) => source.sourceId));
  }, [binder?.generatedAt, sourcesSummary.length]);
  const selectedSet = useMemo(() => new Set(selectedSources), [selectedSources]);
  const chunks = useMemo(() => (binder?.chunks ?? []).filter((chunk) => !chunk.sourceId || selectedSet.has(chunk.sourceId)), [binder, selectedSet]);
  const singleSource = selectedSources.length <= 1;
  const fromSelectedSource = (item) => {
    const citations = item?.resolvedCitations ?? [];
    return !citations.length || citations.some((citation) => selectedSet.has(citation.sourceId));
  };

  const openSource = async (sourceId, page) => {
    try {
      await openSourcePage(sourceId, page);
    } catch (e) {
      toast.error(e.message ?? 'Could not open that page.');
    }
  };

  if (error) {
    return (
      <StudyShell title="Recap unavailable" backTo="/app/binders">
        <div className="shell">
          <Empty
            icon="error"
            title="That binder is not in your library"
            action={
              <Link to="/app/binders" className="btn btn-primary">
                Back to binders
              </Link>
            }
          />
        </div>
      </StudyShell>
    );
  }

  if (!binder) {
    return (
      <StudyShell title="Loading recap" backTo="/app/binders">
        <div className="shell recap-loading" role="status">
          <Spinner size={22} />
          <span>Opening your recap…</span>
        </div>
      </StudyShell>
    );
  }

  if (!binder.recap) {
    return (
      <StudyShell title={binder.name} backTo="/app/binders">
        <div className="shell">
          <Empty
            icon="auto_awesome"
            title="Nothing generated yet"
            body="Go back to this binder and click Generate recap once at least one source is ready."
            action={
              <Link to={`/app/binders/${id}`} className="btn btn-primary">
                Open binder
              </Link>
            }
          />
        </div>
      </StudyShell>
    );
  }

  const { recap, quiz } = binder;

  return (
    <StudyShell title={binder.name} subtitle={`${binder.sourceCount} sources · ${recap.readMinutes ?? ''} min read`} backTo="/app/binders" wide>
      <div className="shell recap-shell">
        <CitationProvider chunks={chunks}>
          <div className="reader-grid">
            <div className="reader-col">
              {sourcesSummary.length > 0 && <SourcesStrip sources={sourcesSummary} selected={selectedSources} onChange={setSelectedSources} />}

              <section className="tldr">
                <h2 className="tldr-title">
                  <Icon name="bolt" size={19} />
                  The short version
                </h2>
                <p>{recap.summary}</p>
              </section>

              <p className="reader-hint">
                <Icon name="touch_app" size={15} />
                Hover any line to see the source it came from. A chip opens that page.
              </p>

              {recap.sections.map((section) => (
                <section key={section.id} className="recap-section">
                  <h2 className="recap-heading">{section.heading}</h2>
                  <ul className="claims">
                    {section.points.filter(fromSelectedSource).map((p) => (
                      <Claim
                        key={p.id}
                        id={p.id}
                        citations={p.citations}
                        confidence={p.confidence}
                        resolvedCitations={p.resolvedCitations}
                        unverified={p.unverified}
                        singleSource={singleSource}
                        onOpenSource={openSource}
                      >
                        {p.text}
                      </Claim>
                    ))}
                  </ul>
                </section>
              ))}

              {recap.keyTerms?.length > 0 && (
                <section className="recap-section">
                  <h2 className="recap-heading">Key terms</h2>
                  <dl className="terms">
                    {recap.keyTerms.filter(fromSelectedSource).map((t) => (
                      <div key={t.term} className="term">
                        <dt>{t.term}</dt>
                        <dd>
                          {t.definition}
                          {t.resolvedCitations?.length > 0 && (
                            <span className="term-cites">
                              {t.resolvedCitations.map((c) => (
                                <button
                                  key={`${c.sourceId}-${c.page}`}
                                  type="button"
                                  className="cite cite-source"
                                  onClick={() => openSource(c.sourceId, c.page)}
                                >
                                  {singleSource ? `p.${c.page}` : `${c.displayName} · p.${c.page}`}
                                </button>
                              ))}
                            </span>
                          )}
                        </dd>
                      </div>
                    ))}
                  </dl>
                </section>
              )}

              {quiz?.questions?.length > 0 && (
                <section className="recap-section" aria-label="Quiz questions">
                  <h2 className="recap-heading">
                    <Icon name="quiz" size={20} />
                    Quiz questions from this recap
                  </h2>
                  <p className="dropped-lede">
                    Shown for reference — every question carries the same source and page citations as the recap
                    above.
                  </p>
                  <ol className="quiz-reference-list">
                    {quiz.questions.filter(fromSelectedSource).map((q, i) => (
                      <li key={q.id} className={`quiz-reference-item ${q.unverified ? 'is-unverified' : ''}`}>
                        <p className="quiz-reference-prompt">
                          <span className="num">{i + 1}.</span> {q.prompt}
                          {q.unverified && (
                            <span className="unverified-flag" title="This question lost its citation during verification.">
                              <Icon name="error" size={15} />
                            </span>
                          )}
                        </p>
                        {q.resolvedCitations?.length > 0 ? (
                          <span className="claim-cites">
                            {q.resolvedCitations.map((c) => (
                              <button
                                key={`${c.sourceId}-${c.page}`}
                                type="button"
                                className="cite cite-source"
                                onClick={() => openSource(c.sourceId, c.page)}
                              >
                                {singleSource ? `p.${c.page}` : `${c.displayName} · p.${c.page}`}
                              </button>
                            ))}
                          </span>
                        ) : (
                          q.citations?.length > 0 && (
                            <span className="claim-cites">
                              {q.citations.map((c) => (
                                <span key={c} className="cite">
                                  {chunks.find((x) => x.id === c)?.label ?? c}
                                </span>
                              ))}
                            </span>
                          )
                        )}
                      </li>
                    ))}
                  </ol>
                </section>
              )}

              {(binder.providers?.length || quiz?.providers?.length) > 0 && (
                <section className="recap-section provenance">
                  <h2>Provider provenance</h2>
                  <p className="dropped-lede">This generated recap keeps its provider record with the selected source provenance.</p>
                  <div className="row wrap gap-2">{[...(binder.providers || []), ...(quiz?.providers || [])].map((provider, index) => <span className="chip" key={`${provider.model || provider.name}-${index}`}><Icon name="verified" size={14} />{provider.name || 'AI provider'}{provider.model ? ` · ${provider.model}` : ''}{provider.role ? ` · ${provider.role}` : ''}</span>)}</div>
                </section>
              )}

              {recap.ungrounded?.length > 0 && (
                <section className="recap-section dropped">
                  <h2 className="recap-heading">
                    <Icon name="rule" size={20} />
                    Dropped from this recap
                  </h2>
                  <p className="dropped-lede">
                    The AI wrote these, but nothing across your sources backs them up.
                  </p>
                  <ul className="dropped-list">
                    {recap.ungrounded.map((u, i) => (
                      <li key={i}>
                        <p className="dropped-claim">{u.text}</p>
                        <p className="dropped-reason">{u.reason}</p>
                      </li>
                    ))}
                  </ul>
                </section>
              )}
            </div>

            <aside className="source-rail" aria-label="Source passages from your binder">
              <p className="rail-title">From {binder.sourceCount} sources</p>
              {chunks.map((c) => (
                <SourceCard key={c.id} chunk={c} />
              ))}
            </aside>
          </div>
        </CitationProvider>
      </div>
    </StudyShell>
  );
}

/**
 * Above the recap: every source in the binder, with how many citations
 * reference it against how many pages it has. A source with plenty of pages
 * but few or no citations is the visible signal that its extraction likely
 * failed — worth noticing before reading the recap, not after wondering why
 * a whole lecture never comes up.
 */
function SourcesStrip({ sources, selected, onChange }) {
  const total = sources.reduce((n, s) => n + s.citationCount, 0);
  const toggle = (sourceId) => onChange(selected.includes(sourceId) ? selected.filter((id) => id !== sourceId) : [...selected, sourceId]);
  return (
    <section className="sources-strip" aria-label="Filter recap by generated source provenance">
      <div className="sources-strip-head">
        <div><h2>Source filter</h2><span className="sources-strip-total">Showing {selected.length} of {sources.length} generated sources</span></div>
        <button type="button" className="btn btn-ghost btn-sm" onClick={() => onChange(sources.map((source) => source.sourceId))}>Show all</button>
      </div>
      <ul className="sources-strip-list">
        {sources.map((s) => {
          const light = s.pageCount > 0 && s.citationCount / s.pageCount < 0.15;
          const active = selected.includes(s.sourceId);
          return (
            <li key={s.sourceId} className={`sources-strip-item ${light ? 'is-light' : ''} ${active ? 'is-active' : ''}`}>
              <button type="button" className="sources-strip-toggle" aria-pressed={active} onClick={() => toggle(s.sourceId)}>
                <Icon name={active ? 'check_box' : 'check_box_outline_blank'} size={17} />
                <span className="truncate sources-strip-name" title={s.displayName}>{s.displayName}</span>
                <span className="sources-strip-count num">{s.citationCount} of {s.pageCount || '?'} page{s.pageCount === 1 ? '' : 's'} cited</span>
              </button>
              {light && (
                <span className="cite cite-missing sources-strip-flag" title="Few citations relative to page count — extraction may have missed most of this file.">
                  <Icon name="warning" size={13} />Low coverage
                </span>
              )}
            </li>
          );
        })}
      </ul>
      <p className="sources-strip-summary">{total} citations across the provenance saved with this generated recap. Filtering never regenerates or changes the source record.</p>
    </section>
  );
}
