import { lazy, Suspense, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { api } from '../lib/api.js';
import { useStore } from '../lib/store.jsx';
import { StudyShell } from '../components/layout/Shells.jsx';
import ErrorBoundary from '../components/ErrorBoundary.jsx';
import { Icon, Spinner, useToast, Segmented } from '../components/ui.jsx';
import useRunner from '../practice/useRunner.js';
import './practice.css';

// CodeMirror is not on the critical path for any other screen, and a student
// who never opens practice should never download it.
const CodeEditor = lazy(() => import('../practice/CodeEditor.jsx'));
// Same reasoning: the agent pulls in the markdown renderer, which the editor
// itself does not need.
const CodeAgent = lazy(() => import('../practice/CodeAgent.jsx'));

/**
 * Practice: write code beside the lecture it came from, and run it.
 *
 * The page has two distinct jobs and they are deliberately separate controls.
 *
 *   Run          — execute what is in the editor and show the output. Always
 *                  available, never grades anything, and is what you reach for
 *                  when you are exploring or debugging.
 *   Check answer — grade against the exercise's tests.
 *
 * An earlier version had one button that did both, and typing `print(21)` to
 * see what happened answered with "0 of 3 tests passing" and three NameErrors.
 * That is a tool telling someone they are wrong for experimenting. Running code
 * and being marked on it are different intentions, so they are different
 * buttons with different results underneath them.
 *
 * The Playground tab exists for the same reason: sometimes you just want to try
 * something. It has no tests, and it needs no backend, so it keeps working even
 * when exercise generation is unavailable.
 */

const PLAYGROUND_ID = '__playground';

const PLAYGROUND_STARTER = {
  python: '# Write anything here and press Run.\nprint("hello")\n',
  javascript: '// Write anything here and press Run.\nconsole.log("hello");\n',
};

/**
 * Did the code simply not define the function the tests call?
 *
 * That is the state you are in before you have written anything, so answering
 * it with one row per test — each a near-identical NameError — is noise at the
 * exact moment a student is least sure what is going on. One sentence saying
 * what to do next is worth more than three stack traces saying the same thing.
 */
function entryMissing(tests, entry) {
  if (!tests?.length || !entry) return false;
  return tests.every(
    (t) => !t.pass && typeof t.actual === 'string' && t.actual.includes(entry) && /not defined/i.test(t.actual),
  );
}

export default function Practice() {
  const { id } = useParams();
  const { materialById } = useStore();
  const toast = useToast();
  const { run, state } = useRunner();

  const [material, setMaterial] = useState(materialById(id) ?? null);
  const [practice, setPractice] = useState(null);
  const [loadFailed, setLoadFailed] = useState(false);
  const [activeId, setActiveId] = useState(PLAYGROUND_ID);
  const [playLang, setPlayLang] = useState('python');
  // Keyed by tab so moving between exercises never discards your work.
  const [drafts, setDrafts] = useState({});
  const [output, setOutput] = useState({});
  const [checks, setChecks] = useState({});
  const [showHint, setShowHint] = useState(false);
  const [helpAvailable, setHelpAvailable] = useState(false);
  const [help, setHelp] = useState({});
  const [helping, setHelping] = useState(false);
  const [agentOpen, setAgentOpen] = useState(false);
  const [exercisesLoading, setExercisesLoading] = useState(true);
  // Whether the student has already started working. Exercises arrive late, and
  // switching tabs out from under someone mid-keystroke would lose their place.
  const touched = useRef(false);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      const [full, set] = await Promise.allSettled([api.materials.get(id), api.practice.get(id)]);
      if (cancelled) return;
      if (full.status === 'fulfilled') setMaterial(full.value);
      if (set.status === 'fulfilled') {
        setPractice(set.value);
        // Land on the first exercise when there is one — the graded path is the
        // point of the page. The playground stays one click away.
        //
        // Only if the student has not started typing: on a first visit these
        // are generated by a model and can take most of a minute to arrive, and
        // by then they may be part-way through something in the Playground.
        if (set.value?.exercises?.length && !touched.current) setActiveId(set.value.exercises[0].id);
      } else {
        // Exercise generation being unavailable must not take the editor with
        // it. The playground needs no backend at all.
        setPractice({ exercises: [], applicable: false });
        setLoadFailed(true);
      }
      setExercisesLoading(false);
    })();
    return () => {
      cancelled = true;
    };
  }, [id]);

  // Only offered when the deployment actually has a coding model configured.
  useEffect(() => {
    let cancelled = false;
    api.practice
      .helpAvailable()
      .then((r) => !cancelled && setHelpAvailable(!!r?.available))
      .catch(() => !cancelled && setHelpAvailable(false));
    return () => {
      cancelled = true;
    };
  }, []);

  const exercises = practice?.exercises ?? [];
  const isPlayground = activeId === PLAYGROUND_ID;
  const exercise = isPlayground ? null : (exercises.find((e) => e.id === activeId) ?? null);

  const language = isPlayground ? playLang : (exercise?.language ?? 'python');
  // The playground keeps a draft per language, so switching to JavaScript and
  // back does not throw away the Python you were part-way through.
  const draftKey = isPlayground ? `${PLAYGROUND_ID}:${playLang}` : activeId;
  const starter = isPlayground ? PLAYGROUND_STARTER[playLang] : (exercise?.starter ?? '');
  const code = drafts[draftKey] ?? starter;

  const result = output[draftKey] ?? null;
  const check = checks[draftKey] ?? null;

  const sources = useMemo(() => {
    if (!exercise || !material?.chunks) return [];
    return exercise.citations.map((c) => material.chunks.find((chunk) => chunk.id === c)).filter(Boolean);
  }, [exercise, material]);

  const busy = state.status === 'running';

  const clear = useCallback(() => {
    setOutput((prev) => ({ ...prev, [draftKey]: null }));
    setChecks((prev) => ({ ...prev, [draftKey]: null }));
    setHelp((prev) => ({ ...prev, [draftKey]: null }));
  }, [draftKey]);

  /** Ask why the failing checks fail. Never asks for, or shows, a solution. */
  const onExplain = useCallback(async () => {
    if (!exercise) return;
    setHelping(true);
    try {
      const failing = (checks[draftKey]?.tests ?? []).filter((t) => !t.pass);
      const res = await api.practice.explain({
        language: exercise.language,
        brief: exercise.brief,
        code,
        failures: failing,
      });
      setHelp((prev) => ({ ...prev, [draftKey]: { text: res.explanation, model: res.model } }));
    } catch (e) {
      setHelp((prev) => ({ ...prev, [draftKey]: { error: e.message ?? 'Could not get help just now.' } }));
    } finally {
      setHelping(false);
    }
  }, [exercise, checks, draftKey, code]);

  /** Run without grading. This is the one that always has to work. */
  const onRun = useCallback(async () => {
    clear();
    const outcome = await run({ language, code, tests: [] });
    setOutput((prev) => ({ ...prev, [draftKey]: outcome }));
  }, [clear, draftKey, language, code, run]);

  /** Run and grade. Only offered on an exercise. */
  const onCheck = useCallback(async () => {
    if (!exercise) return;
    clear();
    const outcome = await run({ language, code, tests: exercise.tests });
    setOutput((prev) => ({ ...prev, [draftKey]: outcome }));
    setChecks((prev) => ({ ...prev, [draftKey]: outcome }));
    if (outcome.ok && outcome.tests.length && outcome.tests.every((t) => t.pass)) {
      toast.success('All checks passed.');
    }
  }, [clear, draftKey, language, code, exercise, run, toast]);

  const onReset = () => {
    setDrafts((prev) => ({ ...prev, [draftKey]: starter }));
    clear();
  };

  const selectTab = (nextId) => {
    setActiveId(nextId);
    setShowHint(false);
  };

  const solved = (e) => checks[e.id]?.tests?.length && checks[e.id].tests.every((t) => t.pass);

  const passed = check?.tests?.filter((t) => t.pass).length ?? 0;
  const missingEntry = exercise && entryMissing(check?.tests, exercise.entry);

  return (
    <StudyShell
      title={material?.title ?? 'Practice'}
      subtitle={isPlayground ? 'Playground — nothing here is marked' : exercise?.concept}
      backTo={`/app/material/${id}`}
      wide
      actions={
        <Link to={`/app/material/${id}`} className="btn btn-ghost btn-sm">
          <Icon name="article" size={17} />
          <span className="action-label">Recap</span>
        </Link>
      }
    >
      <div className="shell practice">
        <div className="practice-grid">
          {/* ------------------------------------------------------ brief */}
          <div className="practice-brief">
            <nav className="practice-tabs" aria-label="Practice">
              <button
                type="button"
                className={`practice-tab ${isPlayground ? 'is-on' : ''}`}
                onClick={() => selectTab(PLAYGROUND_ID)}
                aria-current={isPlayground}
              >
                <Icon name="terminal" size={16} />
                <span className="truncate">Playground</span>
              </button>
              {exercises.map((e, i) => (
                <button
                  key={e.id}
                  type="button"
                  className={`practice-tab ${e.id === activeId ? 'is-on' : ''} ${solved(e) ? 'is-done' : ''}`}
                  onClick={() => selectTab(e.id)}
                  aria-current={e.id === activeId}
                >
                  {solved(e) ? (
                    <Icon name="check_circle" size={15} fill />
                  ) : (
                    <span className="practice-tab-num num">{i + 1}</span>
                  )}
                  <span className="truncate">{e.title}</span>
                </button>
              ))}
              {/* Generated by a model on the first visit, which takes a while.
                  The Playground beside it is usable the whole time. */}
              {exercisesLoading && (
                <span className="practice-tab is-pending" role="status">
                  <Spinner size={14} />
                  <span className="truncate">Writing exercises…</span>
                </span>
              )}
            </nav>

            <h1 className="practice-title">{isPlayground ? 'Playground' : exercise?.title}</h1>
            <p className="practice-lede">
              {isPlayground
                ? 'A blank editor that runs Python or JavaScript. Nothing here is marked — use it to try an idea, or to test one piece of an exercise on its own.'
                : exercise?.brief}
            </p>

            {isPlayground && (
              <div className="field practice-langpick">
                <label>Language</label>
                <Segmented
                  options={[
                    { value: 'python', label: 'Python' },
                    { value: 'javascript', label: 'JavaScript' },
                  ]}
                  value={playLang}
                  onChange={setPlayLang}
                  label="Language"
                />
              </div>
            )}

            {!isPlayground && sources.length > 0 && (
              <div className="practice-sources">
                <p className="practice-sources-head">
                  <Icon name="link" size={15} />
                  From your material
                </p>
                {sources.map((chunk) => (
                  <article key={chunk.id} className="practice-source">
                    <span className="cite">{chunk.label}</span>
                    <p>{chunk.text.slice(0, 320)}</p>
                  </article>
                ))}
              </div>
            )}

            {!isPlayground && exercise?.hint && (
              <div className="practice-hint">
                {showHint ? (
                  <p>
                    <Icon name="lightbulb" size={16} />
                    {exercise.hint}
                  </p>
                ) : (
                  <button type="button" className="btn btn-ghost btn-sm" onClick={() => setShowHint(true)}>
                    <Icon name="lightbulb" size={16} />
                    Show a hint
                  </button>
                )}
              </div>
            )}

            {isPlayground && !exercises.length && (
              <p className="practice-note">
                <Icon name="info" size={15} />
                {loadFailed
                  ? 'Exercises for this material could not be loaded, so only the playground is here. The editor still runs normally.'
                  : (practice.reason ??
                    'This material does not teach programming, so there are no exercises for it — but the playground still works.')}
              </p>
            )}
          </div>

          {/* ----------------------------------------------------- editor */}
          <div className="practice-work">
            <div className="practice-bar">
              <span className="chip practice-lang">{language === 'javascript' ? 'JavaScript' : 'Python'}</span>
              <div className="practice-bar-actions">
                {helpAvailable && (
                  <button
                    type="button"
                    className={`btn btn-sm agent-toggle ${agentOpen ? 'is-open' : ''}`}
                    onClick={() => setAgentOpen((value) => !value)}
                    aria-pressed={agentOpen}
                  >
                    <Icon name="smart_toy" size={17} />
                    Agent
                  </button>
                )}
                <button type="button" className="btn btn-ghost btn-sm" onClick={onReset} disabled={busy}>
                  <Icon name="refresh" size={16} />
                  Reset
                </button>
                <button
                  type="button"
                  className={`btn btn-sm ${exercise ? 'btn-ghost' : 'btn-primary'}`}
                  onClick={onRun}
                  disabled={busy}
                >
                  {busy ? <Spinner size={16} /> : <Icon name="play_arrow" size={18} fill />}
                  {busy ? (state.phase === 'loading-runtime' ? 'Starting Python…' : 'Running…') : 'Run'}
                </button>
                {exercise && (
                  <button type="button" className="btn btn-primary btn-sm" onClick={onCheck} disabled={busy}>
                    <Icon name="checklist" size={17} />
                    Check answer
                  </button>
                )}
              </div>
            </div>

            <div className="practice-editor">
              <Suspense
                fallback={
                  <div className="practice-editor-loading" role="status">
                    <Spinner size={20} />
                    <span>Loading the editor…</span>
                  </div>
                }
              >
                <CodeEditor
                  value={code}
                  language={language}
                  onChange={(next) => {
                    touched.current = true;
                    setDrafts((prev) => ({ ...prev, [draftKey]: next }));
                  }}
                />
              </Suspense>
            </div>

            <div className="practice-output" aria-live="polite">
              {!result && !busy && (
                <p className="practice-output-idle">
                  <Icon name="terminal" size={15} />
                  {exercise
                    ? 'Press Run to see what your code prints, or Check answer to mark it against the exercise. Nothing you write leaves your browser.'
                    : 'Press Run to see what your code prints. Nothing you write leaves your browser.'}
                </p>
              )}

              {result && (
                <>
                  <p className="practice-panel-head">Output</p>
                  {result.error ? (
                    <p className={`practice-error ${result.timedOut ? 'is-timeout' : ''}`}>
                      <Icon name={result.timedOut ? 'timer_off' : 'error'} size={15} />
                      {result.error}
                    </p>
                  ) : result.stdout ? (
                    <pre className="practice-stdout">{result.stdout}</pre>
                  ) : (
                    <p className="practice-output-empty">
                      Your code ran without errors and printed nothing. Use{' '}
                      <code>{language === 'javascript' ? 'console.log(…)' : 'print(…)'}</code> to show a value.
                    </p>
                  )}
                </>
              )}

              {check && !check.error && (
                <div className="practice-checks">
                  {missingEntry ? (
                    <p className="practice-todo">
                      <Icon name="edit_note" size={16} />
                      <span>
                        Your code does not define <code>{exercise.entry}</code> yet. Write that function, then choose
                        Check answer.
                      </span>
                    </p>
                  ) : (
                    <>
                      <p className="practice-panel-head">
                        Checks
                        <span className={passed === check.tests.length ? 'is-pass' : 'is-fail'}>
                          <Icon
                            name={passed === check.tests.length ? 'check_circle' : 'radio_button_unchecked'}
                            size={15}
                            fill
                          />
                          {passed} of {check.tests.length} passing
                        </span>
                      </p>
                      {/* Offered only when something actually failed, and only
                          on a deployment with a coding model. It explains the
                          failure; it never writes the answer. */}
                      {helpAvailable && passed < check.tests.length && (
                        <div className="practice-help">
                          {!help[draftKey] && (
                            <button
                              type="button"
                              className="btn btn-ghost btn-sm"
                              onClick={onExplain}
                              disabled={helping}
                            >
                              {helping ? <Spinner size={15} /> : <Icon name="lightbulb_2" size={16} />}
                              {helping ? 'Reading your code…' : 'Why did this fail?'}
                            </button>
                          )}
                          {help[draftKey]?.error && (
                            <p className="practice-help-error">
                              <Icon name="error" size={15} />
                              {help[draftKey].error}
                            </p>
                          )}
                          {help[draftKey]?.text && (
                            <div className="practice-help-body">
                              <p className="practice-panel-head">
                                Why it fails
                                <span className="practice-help-model">{help[draftKey].model}</span>
                              </p>
                              <p>{help[draftKey].text}</p>
                              <p className="practice-help-note">
                                <Icon name="info" size={14} />
                                Deliberately not the answer — the fix is yours to write.
                              </p>
                            </div>
                          )}
                        </div>
                      )}

                      <ul className="practice-tests">
                        {check.tests.map((t, i) => (
                          <li key={i} className={t.pass ? 'is-pass' : 'is-fail'}>
                            <code className="practice-test-call">{t.call}</code>
                            <span className="practice-test-detail">
                              {t.pass ? (
                                <>gave {t.actual}</>
                              ) : (
                                <>
                                  expected <b>{t.expect}</b>, got <b>{t.actual}</b>
                                </>
                              )}
                            </span>
                          </li>
                        ))}
                      </ul>
                    </>
                  )}
                </div>
              )}
            </div>
          </div>
        </div>

        <Suspense fallback={null}>
          <ErrorBoundary scope="The coding agent">
          <CodeAgent
            open={agentOpen}
            onClose={() => setAgentOpen(false)}
            language={language}
            code={code}
            brief={exercise ? [exercise.title, exercise.brief ?? ''].join('\n\n') : ''}
            output={[result?.stdout, result?.stderr].filter(Boolean).join('\n')}
            allowSolutions={isPlayground}
            onApply={(next) => setDrafts((prev) => ({ ...prev, [draftKey]: next }))}
          />
          </ErrorBoundary>
        </Suspense>
      </div>
    </StudyShell>
  );
}
