export const initialMaterials = [
  { id: 1, name: 'Database Systems — Week 5.pdf', type: 'pdf', date: 'Today', description: 'Normalisation, keys, functional dependencies and SQL joins.', score: 82 },
  { id: 2, name: 'Cybersecurity Fundamentals.pptx', type: 'pptx', date: '14 Aug 2026', description: 'Threat models, authentication and network defence essentials.', score: 71 },
  { id: 3, name: 'Engineering Mathematics 2.docx', type: 'docx', date: '10 Aug 2026', description: 'Laplace transforms, complex numbers and differential equations.', score: 88 },
  { id: 4, name: 'Cloud Architecture Notes.pdf', type: 'pdf', date: '02 Aug 2026', description: 'AWS reliability pillars, serverless patterns and shared responsibility.', score: 63 },
];

export const questions = [
  { topic: 'Normalisation', prompt: 'What is the main purpose of database normalisation?', options: ['To make every query execute faster', 'To reduce redundancy and prevent data anomalies', 'To encrypt sensitive columns', 'To combine all data into one table'], answer: 1, explanation: 'Normalisation gives each fact one reliable home, reducing duplication and update, insert, or delete anomalies.', verified: true },
  { topic: 'Keys', prompt: 'Which statement best describes a primary key?', options: ['It can contain duplicate values', 'It links only two database servers', 'It uniquely identifies each row in a table', 'It is always a single numeric column'], answer: 2, explanation: 'A primary key uniquely identifies a row. It may be one column or a composite of several columns.', verified: true },
  { topic: 'Normalisation', prompt: 'A table is in Third Normal Form (3NF) when it is in 2NF and…', options: ['has no foreign keys', 'contains only numeric values', 'has no transitive dependencies', 'has exactly three columns'], answer: 2, explanation: '3NF removes transitive dependencies: non-key attributes should not depend on other non-key attributes.', verified: true },
  { topic: 'SQL Joins', prompt: 'Which join keeps every row from the left table, even when no match exists?', options: ['INNER JOIN', 'LEFT JOIN', 'CROSS JOIN', 'SELF JOIN'], answer: 1, explanation: 'LEFT JOIN returns all rows from the left table and matching rows from the right, using NULL where no match exists.', verified: true },
  { topic: 'Dependencies', prompt: 'If StudentID determines StudentName, how is that functional dependency written?', options: ['StudentName → StudentID', 'StudentID = StudentName', 'StudentID → StudentName', 'StudentID JOIN StudentName'], answer: 2, explanation: 'A → B means that the value of A uniquely determines the value of B.', verified: true },
  { topic: 'SQL Joins', prompt: 'According to the example, which join is always fastest for large tables?', options: ['INNER JOIN', 'LEFT JOIN', 'CROSS JOIN', 'The source does not establish this'], answer: 3, explanation: 'The material does not provide enough evidence for a universal performance claim, so this item is excluded from scoring.', verified: false },
  { topic: 'Normalisation', prompt: 'What must be removed to move a table from 1NF to 2NF?', options: ['All primary keys', 'Partial dependencies on a composite key', 'Every foreign key', 'All text columns'], answer: 1, explanation: '2NF requires 1NF and removes partial dependencies on only part of a composite key.', verified: true },
  { topic: 'Keys', prompt: 'What does a foreign key usually reference?', options: ['A primary or candidate key in a related table', 'A file stored outside the database', 'Only another foreign key', 'The database password'], answer: 0, explanation: 'A foreign key references a unique key—commonly the primary key—in a related table.', verified: true },
];